# Generated by Django 4.2.5 on 2023-09-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_expired',
        ),
    ]
